version: "3.8"

services:
  client:
    build:
      context: ./client
    image: machinewise-mutha-frontend
    ports:
      - "5173:80"
    depends_on:
      - server
    networks:
      - machinewise-mutha-network

  server:
    build:
      context: ./server
    image: machinewise-mutha-backend
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/mutha
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - machinewise-mutha-network

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    networks:
      - machinewise-mutha-network

volumes:
  dbdata:

networks:
  machinewise-mutha-network:
    driver: bridge
